### ISSUE TITLE
Can't compile 

### ISSUE THREAD

**Issue by bilbolodz** [pagocs/esp32-rflinkmqttgateway#1]
I'm trying to compile code but got error: ESP.h no such file or directory.
I've installed all recommended libraries and board. I've tried with board:
- ESP32 Dev Module
- LOLIN D32

and result is the same.
Arduino: 1.8.13 plaftorm: linux

Any ideas?

**Comment by pagocs** [comment]
Can you check your Arduino folder? The  ESP.h file on my system (macos) is located here ~Documents/Arduino/hardware/espressif/esp32/cores/esp32
and the projects folders location is: ~Documents/Arduino/projects

**Comment by bilbolodz** [comment]
I've managed to compile. It's looks that ESP32 libraries are not ready for linux environment where capital letters in file names does matter. I've do make a lot of symlinks like:
ESP.h -> Esp.h
WifiClient.h -> WiFiClient.h
WiFiUDP.h -> WiFiUdp.h
ledblink.H -> ledblink.h
wificonnect.H -> wificonnect.h etc

Generally: esp32-common library and espressif esp32 arduino package is NOT Linux friendly and require a lot of polishing.

**Comment by pagocs** [comment]
Thanks for sharing with me. I will fix the file name issues.
