### ISSUE TITLE
Filter doesn't work

### ISSUE THREAD

**Issue by neutrino85** [pagocs/esp32-rflinkmqttgateway#2]
Hi,
Thank you for all, i'm using your firmware with 2 rflink and domoticz.
I have an issue with filter.
I add `"Astrell",` in deviceignorelist[] but it filter out all the packets and nothing is published.
Am I doing something wrong ?
```
const char* deviceignorelist[] = {
  // Example:
  // "SelectPlus3" , "Alecto V2" , "TriState" ,
  // "Warema" , "Drayton", "Keeloq" ,
  // "Auriol V2",
  "Astrell",
  // NULL
};
```
Packet i try to filter out :
20;6C;Astrell;ID=0414d8;SWITCH=K0;CMD=ALLOFF;

**Comment by pagocs** [comment]
Sorry for the late answer, but unfortunately I did not got any notification about your request.

About the issue, you need to uncomment the NULL also because that item indicates the end of the list.

**Comment by neutrino85** [comment]
Seems to work great!
Thanks!
